In [5]:
import numpy as np
#addition of array
x=np.array([[1,2],[0,2]])
y=np.array([[0,3],[1,4]])
z=x+y
z

array([[1, 5],
       [1, 6]])

In [2]:
import numpy as np
#multiplying array with a scalar constant
y=np.array([[2,1],[1,3]])
z=2*y
z

array([[4, 2],
       [2, 6]])

In [3]:
#multiplying matrix
a=np.array([[0,1,1],[1,0,1]])
b=np.array([[1,1],[1,1],[-1,1]])
p=np.dot(a,b)
p

array([[0, 2],
       [0, 2]])